builds:
  -
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: 386
    flags: -tags vfs
    hooks:
      pre: go generate
